# Generated by Django 4.2.4 on 2023-09-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_client_email_tag_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tag',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='notes.tag'),
        ),
    ]
